/**
 * @fileOverview Statically defined comparison data for common test automation tools.
 * This data is used to provide instant comparisons without needing an AI call for known tools.
 */

// The canonical order of criteria for display in the comparison table.
export const comparisonCriteriaOrder = [
  'Initial Setup Time',
  'Maintenance Overhead',
  'Test Creation Speed',
  'Script Reusability',
  'Parallel Execution Support',
  'Test Case Creation Effort',
  'Skill Requirement',
  'Overall Automation Coverage',
  'Total Cost of Ownership',
];

// The raw data. Keys are lowercase tool names for easy, case-insensitive lookup.
// The 'Overview' key is used for the tool overviews section above the main table.
export const localToolComparisonData: Record<string, Record<string, string>> = {
  'zeta automation': {
    'Overview': 'A unified, open-source automation framework for high reusability and comprehensive test coverage across multiple application layers.',
    'Initial Setup Time': '2-4 days; framework setup and environment configuration.',
    'Maintenance Overhead': 'Low; utility-driven layers minimize script breakage.',
    'Test Creation Speed': 'High; pre-built templates accelerate authoring.',
    'Script Reusability': 'High; shared libraries and config-driven design.',
    'Parallel Execution Support': 'Excellent; native CI integration for parallel runs.',
    'Test Case Creation Effort': 'Medium; template-based creation simplifies process.',
    'Skill Requirement': 'Moderate; Java and Maven knowledge preferred.',
    'Overall Automation Coverage': 'Very High; unified UI, API, DB, and Security.',
    'Total Cost of Ownership': 'Low; open-source, requires internal infrastructure.',
  },
  'functionize': {
    'Overview': 'An AI-powered testing platform for web applications that automates test creation and maintenance.',
    'Initial Setup Time': '< 1 day; cloud-based, no local setup needed.',
    'Maintenance Overhead': 'Very Low; AI-powered self-healing adapts to UI changes.',
    'Test Creation Speed': 'Very High; uses natural language and visual tools.',
    'Script Reusability': 'Moderate; promotes reusable test steps and flows.',
    'Parallel Execution Support': 'Excellent; cloud infrastructure scales massively.',
    'Test Case Creation Effort': 'Very Low; NLP & visual tools for test creation.',
    'Skill Requirement': 'Low; no coding required for most tasks.',
    'Overall Automation Coverage': 'High; primarily focuses on web UI & E2E.',
    'Total Cost of Ownership': 'High; subscription-based SaaS model.',
  },
  'selenium': {
    'Overview': 'A highly flexible, open-source framework for web browser automation with extensive community support and language bindings.',
    'Initial Setup Time': '1-3 days; requires setting up WebDriver and bindings.',
    'Maintenance Overhead': 'High; brittle without strong framework design.',
    'Test Creation Speed': 'Medium; requires manual scripting for all tests.',
    'Script Reusability': 'High; dependent on user-created framework.',
    'Parallel Execution Support': 'Good; requires setup and configuration of Selenium Grid.',
    'Test Case Creation Effort': 'High; requires coding and element location.',
    'Skill Requirement': 'High; strong programming and framework skills needed.',
    'Overall Automation Coverage': 'Medium; focused exclusively on web browsers.',
    'Total Cost of Ownership': 'Medium; open-source, but high human resource cost.',
  },
  'playwright': {
    'Overview': 'A modern, capable, and reliable framework for end-to-end testing of web applications across all major browsers.',
    'Initial Setup Time': '< 1 day; includes installing package and browsers.',
    'Maintenance Overhead': 'Low to Medium; auto-waits reduce flakiness.',
    'Test Creation Speed': 'High; Codegen tool accelerates script creation.',
    'Script Reusability': 'High; supports Page Object Model and custom functions.',
    'Parallel Execution Support': 'Excellent; built-in support for running tests in parallel.',
    'Test Case Creation Effort': 'Medium; scripting knowledge required, but tools assist.',
    'Skill Requirement': 'Moderate; requires JavaScript/TypeScript skills.',
    'Overall Automation Coverage': 'High; strong support for E2E, API, and component tests.',
    'Total Cost of Ownership': 'Low; open-source, requires skilled resources.',
  },
  'cypress': {
    'Overview': 'An all-in-one testing framework for modern web applications, known for its excellent developer experience and debugging.',
    'Initial Setup Time': '< 1 day; single package installation.',
    'Maintenance Overhead': 'Low to Medium; good selector engine and retry-ability.',
    'Test Creation Speed': 'Very High; interactive runner and excellent debugging tools.',
    'Script Reusability': 'High; custom commands and fixtures support reuse.',
    'Parallel Execution Support': 'Excellent; native support with paid Cypress Cloud dashboard.',
    'Test Case Creation Effort': 'Low to Medium; intuitive API simplifies scripting.',
    'Skill Requirement': 'Moderate; requires JavaScript/TypeScript skills.',
    'Overall Automation Coverage': 'Medium; focused on web component and E2E testing.',
    'Total Cost of Ownership': 'Low to Medium; open-source core with paid cloud features.',
  },
  'testcomplete': {
    'Overview': 'A comprehensive UI test automation tool for desktop, web, and mobile applications with AI-powered object recognition.',
    'Initial Setup Time': '1-2 days; guided installer and configuration.',
    'Maintenance Overhead': 'Medium; AI helps, but updates can require maintenance.',
    'Test Creation Speed': 'High; record-and-replay and keyword views.',
    'Script Reusability': 'Moderate; supports reusable keyword tests and script libraries.',
    'Parallel Execution Support': 'Good; integrates with test management tools for distribution.',
    'Test Case Creation Effort': 'Low; visual tools and scripting are both options.',
    'Skill Requirement': 'Low to Moderate; scripting knowledge is optional.',
    'Overall Automation Coverage': 'Very High; supports desktop, web, and mobile platforms.',
    'Total Cost of Ownership': 'High; requires per-user licensing.',
  },
  'ranorex studio': {
    'Overview': 'A powerful, all-in-one tool for end-to-end testing of desktop, web, and mobile applications with a strong object spy.',
    'Initial Setup Time': '1-2 days; includes environment setup and instrumentation.',
    'Maintenance Overhead': 'Medium; robust object recognition helps, but is not immune to changes.',
    'Test Creation Speed': 'High; codeless editor and full IDE for rapid development.',
    'Script Reusability': 'Good; provides a reusable module and code library system.',
    'Parallel Execution Support': 'Good; can integrate with Selenium Grid for web tests.',
    'Test Case Creation Effort': 'Low; powerful object spy simplifies element identification.',
    'Skill Requirement': 'Low to Moderate; empowers both codeless and code-based testers.',
    'Overall Automation Coverage': 'Very High; excellent for desktop, with strong web/mobile support.',
    'Total Cost of Ownership': 'High; license-based model.',
  },
   'postman': {
    'Overview': 'An API platform for building and using APIs, offering a comprehensive toolset for the entire API lifecycle.',
    'Initial Setup Time': '< 1 day; install app and sign in.',
    'Maintenance Overhead': 'Low; collections and environments simplify management.',
    'Test Creation Speed': 'Very High; GUI for request building, with scripting for assertions.',
    'Script Reusability': 'Good; scripts can be shared within collections and workspaces.',
    'Parallel Execution Support': 'Good; command-line runner (Newman) supports parallel runs.',
    'Test Case Creation Effort': 'Very Low; GUI-based request building and scripting.',
    'Skill Requirement': 'Low; basic scripting knowledge is beneficial but not required.',
    'Overall Automation Coverage': 'Low; focused exclusively on API testing.',
    'Total Cost of Ownership': 'Freemium/Subscription; free for individuals, paid for teams.',
  },
};
