/**
 * @fileOverview Statically defined comparison data for common test automation tools.
 * This data is used to provide instant comparisons without needing an AI call for known tools.
 */

// The canonical order of criteria for display in the comparison table.
export const comparisonCriteriaOrder = [
  'Initial Setup Time',
  'Maintenance Overhead',
  'Test Creation Speed',
  'Script Reusability',
  'Parallel Execution Support',
  'Test Case Creation Effort',
  'Skill Requirement',
  'Overall Automation Coverage',
  'Total Cost of Ownership',
];

// The raw data. Keys are lowercase tool names for easy, case-insensitive lookup.
// The 'Overview' key is used for the tool overviews section above the main table.
export const localToolComparisonData: Record<string, Record<string, string>> = {
  'zeta automation': {
    'Overview': 'A unified, open-source automation framework for high reusability and comprehensive test coverage across multiple application layers.',
    'Initial Setup Time': '2-4 days; framework setup.',
    'Maintenance Overhead': 'Low; utility-driven layers.',
    'Test Creation Speed': 'High; pre-built templates.',
    'Script Reusability': 'High; shared libraries.',
    'Parallel Execution Support': 'Excellent; native CI integration.',
    'Test Case Creation Effort': 'Medium; template-based.',
    'Skill Requirement': 'Moderate; Java & Maven.',
    'Overall Automation Coverage': 'Very High; UI, API, DB, Security.',
    'Total Cost of Ownership': 'Low; open-source.',
  },
  'functionize': {
    'Overview': 'An AI-powered testing platform for web applications that automates test creation and maintenance.',
    'Initial Setup Time': '< 1 day; cloud-based.',
    'Maintenance Overhead': 'Very Low; AI self-healing.',
    'Test Creation Speed': 'Very High; NLP & visual tools.',
    'Script Reusability': 'Moderate; reusable steps/flows.',
    'Parallel Execution Support': 'Excellent; scalable cloud.',
    'Test Case Creation Effort': 'Very Low; NLP & visual tools.',
    'Skill Requirement': 'Low; no coding required.',
    'Overall Automation Coverage': 'High; web UI & E2E focus.',
    'Total Cost of Ownership': 'High; SaaS subscription.',
  },
  'selenium': {
    'Overview': 'A highly flexible, open-source framework for web browser automation with extensive community support and language bindings.',
    'Initial Setup Time': '1-3 days; WebDriver setup.',
    'Maintenance Overhead': 'High; requires strong design.',
    'Test Creation Speed': 'Medium; manual scripting.',
    'Script Reusability': 'High; depends on framework.',
    'Parallel Execution Support': 'Good; requires Selenium Grid.',
    'Test Case Creation Effort': 'High; coding required.',
    'Skill Requirement': 'High; strong coding skills.',
    'Overall Automation Coverage': 'Medium; web browser focus.',
    'Total Cost of Ownership': 'Medium; high resource cost.',
  },
  'playwright': {
    'Overview': 'A modern, capable, and reliable framework for end-to-end testing of web applications across all major browsers.',
    'Initial Setup Time': '< 1 day; package install.',
    'Maintenance Overhead': 'Low-Medium; auto-waits.',
    'Test Creation Speed': 'High; Codegen tool.',
    'Script Reusability': 'High; supports POM.',
    'Parallel Execution Support': 'Excellent; native support.',
    'Test Case Creation Effort': 'Medium; scripting assisted.',
    'Skill Requirement': 'Moderate; JS/TS skills.',
    'Overall Automation Coverage': 'High; E2E, API, components.',
    'Total Cost of Ownership': 'Low; open-source.',
  },
  'cypress': {
    'Overview': 'An all-in-one testing framework for modern web applications, known for its excellent developer experience and debugging.',
    'Initial Setup Time': '< 1 day; single package.',
    'Maintenance Overhead': 'Low-Medium; good retry-ability.',
    'Test Creation Speed': 'Very High; interactive runner.',
    'Script Reusability': 'High; custom commands.',
    'Parallel Execution Support': 'Excellent; paid cloud option.',
    'Test Case Creation Effort': 'Low-Medium; intuitive API.',
    'Skill Requirement': 'Moderate; JS/TS skills.',
    'Overall Automation Coverage': 'Medium; web component/E2E focus.',
    'Total Cost of Ownership': 'Low-Medium; freemium cloud.',
  },
  'testcomplete': {
    'Overview': 'A comprehensive UI test automation tool for desktop, web, and mobile applications with AI-powered object recognition.',
    'Initial Setup Time': '1-2 days; guided setup.',
    'Maintenance Overhead': 'Medium; AI-assisted.',
    'Test Creation Speed': 'High; record & replay.',
    'Script Reusability': 'Moderate; keyword tests.',
    'Parallel Execution Support': 'Good; integrates for distribution.',
    'Test Case Creation Effort': 'Low; visual & scripting.',
    'Skill Requirement': 'Low-Moderate; scripting optional.',
    'Overall Automation Coverage': 'Very High; desktop, web, mobile.',
    'Total Cost of Ownership': 'High; per-user license.',
  },
  'ranorex studio': {
    'Overview': 'A powerful, all-in-one tool for end-to-end testing of desktop, web, and mobile applications with a strong object spy.',
    'Initial Setup Time': '1-2 days; setup & instrumentation.',
    'Maintenance Overhead': 'Medium; robust object recognition.',
    'Test Creation Speed': 'High; codeless editor & IDE.',
    'Script Reusability': 'Good; reusable modules.',
    'Parallel Execution Support': 'Good; Selenium Grid integration.',
    'Test Case Creation Effort': 'Low; powerful object spy.',
    'Skill Requirement': 'Low-Moderate; codeless & code.',
    'Overall Automation Coverage': 'Very High; desktop, web, mobile.',
    'Total Cost of Ownership': 'High; license-based.',
  },
   'postman': {
    'Overview': 'An API platform for building and using APIs, offering a comprehensive toolset for the entire API lifecycle.',
    'Initial Setup Time': '< 1 day; app install.',
    'Maintenance Overhead': 'Low; collections simplify.',
    'Test Creation Speed': 'Very High; GUI builder.',
    'Script Reusability': 'Good; shared scripts.',
    'Parallel Execution Support': 'Good; via Newman CLI.',
    'Test Case Creation Effort': 'Very Low; GUI & scripting.',
    'Skill Requirement': 'Low; scripting optional.',
    'Overall Automation Coverage': 'Low; API testing focus.',
    'Total Cost of Ownership': 'Freemium/Subscription.',
  },
};
