
// src/lib/tool-options.ts
export const automationToolOptions = [
  { value: "accelq", label: "ACCELQ (AI, Codeless)" },
  { value: "appium", label: "Appium" },
  { value: "applitools", label: "Applitools (Visual AI)" },
  { value: "browserstack_automate", label: "BrowserStack Automate (Cloud Platform)" },
  { value: "cucumber", label: "Cucumber (BDD)" },
  { value: "cypress", label: "Cypress" },
  { value: "detox", label: "Detox (Mobile E2E for React Native)" },
  { value: "eggplant", label: "Eggplant (by Keysight)" },
  { value: "espresso", label: "Espresso (Android UI Testing)" },
  { value: "functionize", label: "Functionize (AI)" },
  { value: "gatling", label: "Gatling (Performance)" },
  { value: "gauge", label: "Gauge (by ThoughtWorks)" },
  { value: "ghost_inspector", label: "Ghost Inspector (Codeless, UI Monitoring)" },
  { value: "k6", label: "Grafana k6 (Performance)" },
  { value: "jmeter", label: "JMeter" },
  { value: "karate_dsl", label: "Karate DSL (API/UI)" },
  { value: "katalon_studio", label: "Katalon Studio" },
  { value: "kobiton", label: "Kobiton (Mobile Cloud)" },
  { value: "lambdatest", label: "LambdaTest (Cloud Platform)" },
  { value: "leapwork", label: "Leapwork (Codeless)" },
  { value: "mabl", label: "Mabl (AI)" },
  { value: "uft_one", label: "Micro Focus UFT One" },
  { value: "newman", label: "Newman (Postman CLI)" },
  { value: "perfecto", label: "Perfecto (Mobile & Web Cloud)" },
  { value: "percy", label: "Percy (Visual Testing, AI)" },
  { value: "playwright", label: "Playwright" },
  { value: "puppeteer", label: "Puppeteer" },
  { value: "ranorex", label: "Ranorex" },
  { value: "reflect_run", label: "Reflect (Codeless, AI)" },
  { value: "restassured", label: "Rest Assured" },
  { value: "robot_framework", label: "Robot Framework" },
  { value: "sahi_pro", label: "Sahi Pro (Web Automation)" },
  { value: "saucelabs", label: "Sauce Labs (Cloud Platform)" },
  { value: "selenium", label: "Selenium" },
  { value: "soapui", label: "SoapUI" },
  { value: "specflow", label: "SpecFlow (BDD for .NET)" },
  { value: "testcafe", label: "TestCafe" },
  { value: "testcomplete", label: "TestComplete" },
  { value: "testim", label: "Testim (AI)" },
  { value: "testsigma", label: "TestSigma (AI, Low-code)" },
  { value: "tricentis_tosca", label: "Tricentis Tosca" },
  { value: "webdriverio", label: "WebdriverIO" },
  { value: "winappdriver", label: "WinAppDriver" },
  { value: "xcuitest", label: "XCUITest (iOS UI Testing)" },
  { value: "zeta_automation", label: "ZeTA Automation" },
];
