/**
 * @fileOverview Statically defined comparison data for common test automation tools.
 * This data is used to provide instant comparisons without needing an AI call for known tools.
 */

// The canonical order of criteria for display in the comparison table.
export const comparisonCriteriaOrder = [
  'Initial Setup Time',
  'Maintenance Overhead',
  'Test Creation Speed',
  'Script Reusability',
  'Parallel Execution Support',
  'Test Case Creation Effort',
  'Skill Requirement',
  'Overall Automation Coverage',
  'Total Cost of Ownership',
];

// The raw data. Keys are lowercase tool names for easy, case-insensitive lookup.
// The 'Overview' key is used for the tool overviews section above the main table.
export const localToolComparisonData: Record<string, Record<string, string>> = {
  'zeta automation': {
    'Overview': 'A unified, open-source automation framework for high reusability and comprehensive test coverage across multiple application layers.',
    'Initial Setup Time': '2-4 days; framework setup and environment configuration.',
    'Maintenance Overhead': 'Low; utility-driven layers minimize script breakage.',
    'Test Creation Speed': 'High; pre-built templates accelerate authoring.',
    'Script Reusability': 'High; shared libraries and config-driven design.',
    'Parallel Execution Support': 'Excellent; native CI integration for parallel runs.',
    'Test Case Creation Effort': 'Medium; template-based creation simplifies process.',
    'Skill Requirement': 'Moderate; Java and Maven knowledge preferred.',
    'Overall Automation Coverage': 'Very High; unified UI, API, DB, and Security.',
    'Total Cost of Ownership': 'Low; open-source, requires internal infrastructure.',
  },
  'functionize': {
    'Overview': 'An AI-powered testing platform for web applications that automates test creation and maintenance.',
    'Initial Setup Time': '< 1 day; cloud-based, no local setup needed.',
    'Maintenance Overhead': 'Very Low; AI-powered self-healing adapts to UI changes.',
    'Test Creation Speed': 'Very High; uses natural language and visual tools.',
    'Script Reusability': 'Moderate; promotes reusable test steps and flows.',
    'Parallel Execution Support': 'Excellent; cloud infrastructure scales massively.',
    'Test Case Creation Effort': 'Very Low; NLP & visual tools for test creation.',
    'Skill Requirement': 'Low; no coding required for most tasks.',
    'Overall Automation Coverage': 'High; primarily focuses on web UI & E2E.',
    'Total Cost of Ownership': 'High; subscription-based SaaS model.',
  },
  'selenium': {
    'Overview': 'A highly flexible, open-source framework for web browser automation with extensive community support and language bindings.',
    'Initial Setup Time': '1-3 days; requires setting up WebDriver and bindings.',
    'Maintenance Overhead': 'High; brittle without strong framework design.',
    'Test Creation Speed': 'Medium; requires manual scripting for all tests.',
    'Script Reusability': 'High; dependent on user-created framework.',
    'Parallel Execution Support': 'Good; requires setup and configuration of Selenium Grid.',
    'Test Case Creation Effort': 'High; requires coding and element location.',
    'Skill Requirement': 'High; strong programming and framework skills needed.',
    'Overall Automation Coverage': 'Medium; focused exclusively on web browsers.',
    'Total Cost of Ownership': 'Medium; open-source, but high human resource cost.',
  },
  'playwright': {
    'Overview': 'A modern, capable, and reliable framework for end-to-end testing of web applications across all major browsers.',
    'Initial Setup Time': '< 1 day',
    'Maintenance Overhead': 'Medium',
    'Test Creation Speed': 'High',
    'Script Reusability': 'High',
    'Parallel Execution Support': 'Excellent',
    'Test Case Creation Effort': 'Medium',
    'Skill Requirement': 'Moderate (JS/TS)',
    'Overall Automation Coverage': 'Medium (Web/API)',
    'Total Cost of Ownership': 'Low (Open Source)',
  },
  'cypress': {
    'Overview': 'An all-in-one testing framework for modern web applications, known for its excellent developer experience and debugging.',
    'Initial Setup Time': '< 1 day',
    'Maintenance Overhead': 'Medium',
    'Test Creation Speed': 'Very High',
    'Script Reusability': 'Moderate',
    'Parallel Execution Support': 'Good',
    'Test Case Creation Effort': 'Medium',
    'Skill Requirement': 'Moderate (JS/TS)',
    'Overall Automation Coverage': 'Medium (Web Only)',
    'Total Cost of Ownership': 'Low (OSS + Paid Dash)',
  },
  'testcomplete': {
    'Overview': 'A comprehensive UI test automation tool for desktop, web, and mobile applications with AI-powered object recognition.',
    'Initial Setup Time': '1-2 days',
    'Maintenance Overhead': 'Medium',
    'Test Creation Speed': 'High (Record/Replay)',
    'Script Reusability': 'Moderate',
    'Parallel Execution Support': 'Good',
    'Test Case Creation Effort': 'Low',
    'Skill Requirement': 'Low to Moderate',
    'Overall Automation Coverage': 'Very High',
    'Total Cost of Ownership': 'High (License)',
  },
  'ranorex studio': {
    'Overview': 'A powerful, all-in-one tool for end-to-end testing of desktop, web, and mobile applications with a strong object spy.',
    'Initial Setup Time': '1-2 days',
    'Maintenance Overhead': 'Medium',
    'Test Creation Speed': 'High',
    'Script Reusability': 'Good',
    'Parallel Execution Support': 'Good',
    'Test Case Creation Effort': 'Low',
    'Skill Requirement': 'Low to Moderate',
    'Overall Automation Coverage': 'Very High',
    'Total Cost of Ownership': 'High (License)',
  },
   'postman': {
    'Overview': 'An API platform for building and using APIs, offering a comprehensive toolset for the entire API lifecycle.',
    'Initial Setup Time': '< 1 day',
    'Maintenance Overhead': 'Low',
    'Test Creation Speed': 'Very High',
    'Script Reusability': 'Good',
    'Parallel Execution Support': 'Good (with Newman)',
    'Test Case Creation Effort': 'Very Low',
    'Skill Requirement': 'Low',
    'Overall Automation Coverage': 'Low (API Only)',
    'Total Cost of Ownership': 'Freemium/Subscription',
  },
};
